### ISSUE TITLE
Can we login using android env?

### ISSUE THREAD

**Issue by hiwaleakshay** [AragurDEV/yowsup#18] opened 2017-11-17 02:49 UTC
i know we can register using android env. But unable to login using android.
All we can do is login using s40 and registering using android? 
did this fork works with android env login?

**Comment by galaxyitcenter** [comment] 2017-11-17 05:31
Not able to login via android yet

**Comment by hbutau** [comment] 2017-11-26 06:50
Any joy with success login with Android?

**Comment by AragurDEV** [comment] 2017-11-27 10:33
Duplicate of #12

**Closed by AragurDEV** 2017-11-27 10:33 UTC
Labels: duplicate
