### ISSUE TITLE
Not receiving messages from new numbers

### ISSUE THREAD

**Issue by BrendoBomfim** [AragurDEV/yowsup#70] opened 2018-04-19 18:52 UTC
I'm receiving this error when new numbers send me messages
```
WARNING:yowsup.layers.axolotl.layer_receive:InvalidMessage or InvalidKeyIdException for 55XXXXXXXXXX, going to send a retry
INFO:yowsup.layers.axolotl.layer_receive:Trying GetKeys for 55XXXXXXXXXX, getting keys now
```

I've found that it breaks when executing this line in layers.axolotl.layer_receive on line 155

`plaintext = sessionCipher.decryptPkmsg(preKeyWhisperMessage)`

I can solve this error if I delete my axolotl.db, but  I can't do this to every new message of new client. Dou you guys know any way to fix this definitely ?

**Comment by jonnym1** [comment] 2018-04-19 21:40
This started happening to me about a week ago, also unreliable sending messages to groups. I have not been able to find a solution.

**Comment by pabloruan0710** [comment] 2018-04-20 11:29
Hi @BrendoBomfim  and @jonnym1, I fixed this with code below
file: yowsup/layers/axolotl/layer_receive.py

In function **def handleEncMessage(self, node):**

Search except (InvalidMessageException, InvalidKeyIdException) as e:

```
except (InvalidMessageException, InvalidKeyIdException) as e
            logger.warning("InvalidMessage or KeyId for %s, going to send a retry", encMessageProtocolEntity.getAuthor(False))
            
            from yowsup.layers.axolotl.protocolentities.iq_key_get import GetKeysIqProtocolEntity
            entity = GetKeysIqProtocolEntity([encMessageProtocolEntity.getAuthor(False)])
            logger.info("[pabloruan0710]: Trying GetKeys for %s  getting keys now", encMessageProtocolEntity.getAuthor(False))

            retry = RetryOutgoingReceiptProtocolEntity.fromMessageNode(node, self.store.getLocalRegistrationId())
            self.toLower(retry.toProtocolTreeNode())
```

**Comment by AragurDEV** [comment] 2018-04-20 12:12
@pabloruan0710
Thanks for your work!
Could you create a pull request so we can fix it for all users?

**Comment by mikesalmonuk** [comment] 2018-04-20 12:15
This looks like it's the same code that's already in `https://github.com/AragurDEV/yowsup/blob/master/yowsup/layers/axolotl/layer_receive.py#L109`
Unless I'm missing something?

**Comment by BrendoBomfim** [comment] 2018-04-20 15:10
Hey guys, thanks for your time, sadly @mikesalmonuk , @pabloruan0710 this is what I have currently, and I already  erased my .yowsup folder but It happened again today. 
It does prints that line twice
`InvalidMessage or KeyId for %s, going to send a retry`
 and then stop working due to lost ACKs

**Comment by mikesalmonuk** [comment] 2018-04-20 15:12
Are you sure you have the latest code? Because that error message you've got isn't actually anywhere in the latest codebase...

**Comment by BrendoBomfim** [comment] 2018-04-20 18:39
@mikesalmonuk Yeah, I pretty sure, but what errors do you mean?

**Comment by mikesalmonuk** [comment] 2018-04-21 09:51
@BrendoBomfim : you said it does prints that line twice
`InvalidMessage or KeyId for %s, going to send a retry`
Thought you meant it in the error log you were seeing that twice.
Was just commented that that bit of code (or message) isn't actually in the codebase, so not sure where you're seeing that?

**Comment by BrendoBomfim** [comment] 2018-04-24 20:58
But it is just like @pabloruan0710 said. I have deleted many times my axolot.db but every new number I get the same error again.

**Comment by BrendoBomfim** [comment] 2018-04-25 13:17
Today deleting the .yowsup folder didn't solved, I had to register again and then delete .yowsup to get it to work again.

**Comment by AragurDEV** [comment] 2018-04-25 17:27
Okay this is fixed in the latest python-axotol version.
I will inform you when my changes are ready.

**Comment by BrendoBomfim** [comment] 2018-04-25 18:37
Great, do you have any idea when it will be finished?

**Comment by AragurDEV** [comment] 2018-05-06 14:48
So now the repo is updated.
Please reinstall yowsup and python-axotol (my fork) and report back

**Comment by juanpmarin** [comment] 2018-06-07 19:29
@AragurDEV I installed your python-axolotl fork and I'm receiving "InvalidMessage or InvalidKeyIdException for *******, going to send a retry" and the message is never decrypted,
it happens every time a new number writes

**Comment by pabloruan0710** [comment] 2018-06-07 19:37
@juanpmarin, @AragurDEV  I Have same problem.

**Comment by naushrambo** [comment] 2018-07-13 00:42
@AragurDEV @BrendoBomfim  Did u find any fix?

**Comment by AragurDEV** [comment] 2018-07-16 21:23
I'm closing this now.
It seems to be a duplicate of #79

**Closed by AragurDEV** 2018-07-16 21:23 UTC
Labels: on_hold
